language: node_js
node_js:
  - "10"
  - "8"
  - "6"
  - "4"
  - "iojs"
  - "0.12"
  - "0.10"
cache: yarn
before_install:
  - nvm install-latest-npm
script:
  - if [ "${LINT-}" = 'true']; then npm run lint; fi
  - if [ "${TEST-}" = 'true' ]; then npm run tests-only; fi
env:
  - TEST=true
matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: LINT=true
