language: node_js
node_js:
  - "15"
  - "14"
  - "12"
  - "10"
  - "8"
cache: yarn
before_install:
  - nvm install-latest-npm
  - npm install -g pnpm@3
script:
  - if [ "${LINT-}" = 'true']; then npm run lint; fi
  - if [ "${TEST-}" = 'true' ]; then npm run tests-only; fi
env:
  - TEST=true
matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: LINT=true
