name: 'Tests: node.js'

on: [pull_request]

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.requireds }}
      minors: ${{ steps.set-matrix.outputs.optionals }}
    steps:
      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          preset: '>=8'
          type: 'majors'

  latest-ubuntu:
    needs: [matrix]
    name: 'latest majors (ubuntu)'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.latest) }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install -g pnpm@3 yarn@1
      - run: npm run tests-only

  latest-windows:
    needs: [matrix]
    name: 'latest majors (windows)'
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.latest) }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm cache clean --force
      - run: npm install -f -g pnpm@3 yarn@1
      - run: npm run tests-only

  node:
    name: 'node 8+'
    needs: [latest-ubuntu, latest-windows]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
